import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from '@/stories/Head/Header/Header'
import { Navbar } from '@/stories/Head/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <Navbar
          items={[
            {
              href: '/#',
              label: 'All'
            },
            {
              href: '/#',
              label: 'Front'
            },
            {
              href: '/#',
              label: 'Back'
            },
            {
              href: '/#',
              label: 'Full'
            }
          ]}
        />
        <main>{children}</main>
      </body>
    </html>
  )
}
